# Generated by Django 4.1.1 on 2022-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dummy', '0006_remove_dimlamp_chandelier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeGrinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(verbose_name='Количество порций')),
                ('grind_size', models.IntegerField(verbose_name='Размер помола')),
                ('is_switched_on', models.BooleanField(blank=True, default=False, verbose_name='Включена')),
            ],
        ),
    ]
